PROD-246: window.location was giving the compiler an issue.
* error TS2450: Left-hand side of assignment expression cannot be a constant or a read-only property.
* Fix was that we need to set the location.href, not location directly.